add more details about the mock implementation
lionel1704/safe_client_libs-wiki pull request #1
Opened 2019-05-17 08:17 UTC by lionel1704

2019-05-17 09:00 UTC, mrcnski requested changes

2019-05-17 09:00 UTC, mrcnski commented on Mock-Implementation.md
> +It can be configured, see [Configuration Parameters](./Mock-vs.-non-mock#configuration-parameters).
Looks like you removed the blank line before this line, which causes it to be included in the previous bullet point when rendering.

2019-05-17 09:00 UTC, mrcnski commented on Mock-Implementation.md
> +This module has the same interface as [routing](https://github.com/maidsafe/routing) and works with the mock vault instead of vaults. All of the operations are mocked, but made to be as realistic as
Looks like you removed the code marks around "sleep" (was `sleep` before).

2019-05-17 09:00 UTC, mrcnski commented on Mock-Implementation.md
> +The client manager authority maps a client's XoR name (i.e. SHA3 hash of the Client's public key) to a mock account object. This object keeps a track of the number of mutations performed and the rema
This paragraph repeats some information from the previous paragraph, e.g.:

> This object keeps a track of the number of mutations performed and the remaining mutations available ...

2019-05-17 09:00 UTC, mrcnski commented on Mock-Implementation.md
> +When testing, separate instances of `MockRouting` can be created with custom configuration parameters. For example, to turn off the mutation limit for one test only. This can be done with the `setup_
This is an incomplete sentence (has no subject) and does not flow well:

> For example, to turn off the mutation limit for one test only.

Not sure why it was changed, tbh.

2019-05-17 09:13 UTC, lionel1704 commented on Mock-Implementation.md
> +The client manager authority maps a client's XoR name (i.e. SHA3 hash of the Client's public key) to a mock account object. This object keeps a track of the number of mutations performed and the rema
Oops! I meant to replace the first para with the second one. Will update :+1

2019-05-17 09:26 UTC, m-cat commented on Mock-Implementation.md
> +The client manager authority maps a client's XoR name (i.e. SHA3 hash of the Client's public key) to a mock account object. This object keeps a track of the number of mutations performed and the rema
One more thing, can this paragraph be broken up as it is a bit long? For example a new paragraph can be started at "Multiple accounts can...", or elsewhere as you see fit.

2019-05-21 14:25 UTC, mrcnski requested changes

2019-05-21 14:25 UTC, m-cat commented on _Sidebar.md
> +    * [Mock implementation](./Mock-Implementation)
One final thing: can we change the name of the file to "Mock implementation"? Minor point but it's the convention we've been following (for simplicity and consistency).

2019-05-21 15:58 UTC, m-cat commented on _Sidebar.md
> +    * [Mock implementation](./Mock-Implementation)
("implementation" in lowercase)

2019-05-21 17:01 UTC, mrcnski approved these changes

2019-05-21 17:16 UTC, merged